//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gecko.NCore.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gecko.NCore.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data object must inherit INotifyPropertyChanged in order to support change tracking..
        /// </summary>
        internal static string ChangeTrackingIsOnlySupportedForINotifyPropertyChanged {
            get {
                return ResourceManager.GetString("ChangeTrackingIsOnlySupportedForINotifyPropertyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A stored query cannot contain additional predicates..
        /// </summary>
        internal static string DataObjectQueryProvider_ExecuteCore_A_stored_query_cannot_contain_additional_predicates {
            get {
                return ResourceManager.GetString("DataObjectQueryProvider_ExecuteCore_A_stored_query_cannot_contain_additional_pred" +
                        "icates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation is only supported within the scope of a valid EphorteContext instance..
        /// </summary>
        internal static string EphorteContext_Current_InvalidOperation {
            get {
                return ResourceManager.GetString("EphorteContext_Current_InvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data object name must be defined as a data object in the configured object model service..
        /// </summary>
        internal static string EphorteContext_Query_DataObjectName_ArgumentOutOfRange {
            get {
                return ResourceManager.GetString("EphorteContext_Query_DataObjectName_ArgumentOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type cannot be found..
        /// </summary>
        internal static string EphorteContext_Query_The_type_cannot_be_found {
            get {
                return ResourceManager.GetString("EphorteContext_Query_The_type_cannot_be_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The registry entry must have a valid CaseId..
        /// </summary>
        internal static string FunctionManagerExtensions_ApproveRegistryEntry_The_registry_entry_must_have_a_valid_CaseId {
            get {
                return ResourceManager.GetString("FunctionManagerExtensions_ApproveRegistryEntry_The_registry_entry_must_have_a_val" +
                        "id_CaseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The registry entry must have a valid Id..
        /// </summary>
        internal static string FunctionManagerExtensions_ApproveRegistryEntry_The_registry_entry_must_have_a_valid_Id {
            get {
                return ResourceManager.GetString("FunctionManagerExtensions_ApproveRegistryEntry_The_registry_entry_must_have_a_val" +
                        "id_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The case must have a valid Id..
        /// </summary>
        internal static string FunctionManagerExtensions_The_case_must_have_a_valid_Id {
            get {
                return ResourceManager.GetString("FunctionManagerExtensions_The_case_must_have_a_valid_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recipient must have a valid Id..
        /// </summary>
        internal static string FunctionManagerExtensions_The_recipient_must_have_a_valid_Id {
            get {
                return ResourceManager.GetString("FunctionManagerExtensions_The_recipient_must_have_a_valid_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recipient must have a valid RegistryEntryId..
        /// </summary>
        internal static string FunctionManagerExtensions_The_recipient_must_have_a_valid_RegistryEntryId {
            get {
                return ResourceManager.GetString("FunctionManagerExtensions_The_recipient_must_have_a_valid_RegistryEntryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sender/recipient must have a valid Id..
        /// </summary>
        internal static string FunctionManagerExtensions_The_sender_recipient_must_have_a_valid_Id {
            get {
                return ResourceManager.GetString("FunctionManagerExtensions_The_sender_recipient_must_have_a_valid_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The task must have a valid Id..
        /// </summary>
        internal static string FunctionManagerExtensions_The_task_must_have_a_valid_Id {
            get {
                return ResourceManager.GetString("FunctionManagerExtensions_The_task_must_have_a_valid_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expressions of type &apos;{0}&apos; are not supported in primary key predicates..
        /// </summary>
        internal static string KeySelectorVisitor_VisitBinary_Expressions_of_type_0_are_not_supported_in_primary_key_predicates {
            get {
                return ResourceManager.GetString("KeySelectorVisitor_VisitBinary_Expressions_of_type_0_are_not_supported_in_primary" +
                        "_key_predicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The right operand of a binary expression must be a constant..
        /// </summary>
        internal static string KeySelectorVisitor_VisitBinary_The_right_operand_of_a_binary_expression_must_be_a_constant {
            get {
                return ResourceManager.GetString("KeySelectorVisitor_VisitBinary_The_right_operand_of_a_binary_expression_must_be_a" +
                        "_constant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member &quot;{0}&quot; does not exist on the type &quot;{1}&quot;..
        /// </summary>
        internal static string MemberNotFound {
            get {
                return ResourceManager.GetString("MemberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &quot;{0}&quot; specified in ServiceModelContextConfiguration.ObjectModelServiceVersion is not support..
        /// </summary>
        internal static string ObjectModelAdapterFactory_Create_ObjectModelServiceVersion_NotSupported {
            get {
                return ResourceManager.GetString("ObjectModelAdapterFactory_Create_ObjectModelServiceVersion_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary conditions with two constants as operands are not supported..
        /// </summary>
        internal static string PredicateVisitor_VisitBinary_Binary_conditions_with_two_constants_as_operands_are_not_supported {
            get {
                return ResourceManager.GetString("PredicateVisitor_VisitBinary_Binary_conditions_with_two_constants_as_operands_are" +
                        "_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property can only be accessed in the scope of an EphorteContext..
        /// </summary>
        internal static string PropertyCanOnlyBeAccessedInTheScopeOfEphorteContext {
            get {
                return ResourceManager.GetString("PropertyCanOnlyBeAccessedInTheScopeOfEphorteContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties on QueryContext.Current are only supported in a Linq query based on IEphorteContext..
        /// </summary>
        internal static string QueryContext_Properties_on_QueryContext_Current_are_only_supported_in_a_Linq_query_based_on_IEphorteContext {
            get {
                return ResourceManager.GetString("QueryContext_Properties_on_QueryContext_Current_are_only_supported_in_a_Linq_quer" +
                        "y_based_on_IEphorteContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member &apos;{0}&apos; on type &apos;{1}&apos; is not supported..
        /// </summary>
        internal static string QueryContextVisitor_VisitMember_The_member_0_on_type_1_is_not_supported {
            get {
                return ResourceManager.GetString("QueryContextVisitor_VisitMember_The_member_0_on_type_1_is_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method &apos;{0}&apos; on &apos;{1}&apos; is not supported..
        /// </summary>
        internal static string QueryContextVisitor_VisitMethodCall_The_method_0_on_1_is_not_supported {
            get {
                return ResourceManager.GetString("QueryContextVisitor_VisitMethodCall_The_method_0_on_1_is_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection is read-only..
        /// </summary>
        internal static string The_collection_is_read_only {
            get {
                return ResourceManager.GetString("The_collection_is_read_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method call &apos;{0}&apos; on type &apos;{1}&apos; is not supported..
        /// </summary>
        internal static string VisitMethodCall_The_method_call_0_on_type_1_is_not_supported {
            get {
                return ResourceManager.GetString("VisitMethodCall_The_method_call_0_on_type_1_is_not_supported", resourceCulture);
            }
        }
    }
}
