//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gecko.NCore.Client.Documents.V2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EphorteIdentity", Namespace="http://schemas.datacontract.org/2004/07/Ephorte.ServiceModel.Contracts")]
    [System.SerializableAttribute()]
    public partial class EphorteIdentity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DatabaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalSystemNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Database {
            get {
                return this.DatabaseField;
            }
            set {
                if ((object.ReferenceEquals(this.DatabaseField, value) != true)) {
                    this.DatabaseField = value;
                    this.RaisePropertyChanged("Database");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string ExternalSystemName {
            get {
                return this.ExternalSystemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalSystemNameField, value) != true)) {
                    this.ExternalSystemNameField = value;
                    this.RaisePropertyChanged("ExternalSystemName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BeginReadDocumentResponse", Namespace="http://schemas.datacontract.org/2004/07/Ephorte.ServiceModel.Contracts.Documents." +
        "V2")]
    [System.SerializableAttribute()]
    public partial class BeginReadDocumentResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ContentLengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ContextIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilenameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ContentLength {
            get {
                return this.ContentLengthField;
            }
            set {
                if ((this.ContentLengthField.Equals(value) != true)) {
                    this.ContentLengthField = value;
                    this.RaisePropertyChanged("ContentLength");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ContextId {
            get {
                return this.ContextIdField;
            }
            set {
                if ((this.ContextIdField.Equals(value) != true)) {
                    this.ContextIdField = value;
                    this.RaisePropertyChanged("ContextId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filename {
            get {
                return this.FilenameField;
            }
            set {
                if ((object.ReferenceEquals(this.FilenameField, value) != true)) {
                    this.FilenameField = value;
                    this.RaisePropertyChanged("Filename");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.gecko.no/ephorte/services/documents/v2", ConfigurationName="Documents.V2.Documents")]
    public interface Documents {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gecko.no/ephorte/services/documents/v2/Documents/BeginCheckin", ReplyAction="http://www.gecko.no/ephorte/services/documents/v2/Documents/BeginCheckinResponse")]
        System.Guid BeginCheckin(Gecko.NCore.Client.Documents.V2.EphorteIdentity identity, int documentId, int version, string variant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gecko.no/ephorte/services/documents/v2/Documents/WriteCheckinChunk", ReplyAction="http://www.gecko.no/ephorte/services/documents/v2/Documents/WriteCheckinChunkResp" +
            "onse")]
        void WriteCheckinChunk(Gecko.NCore.Client.Documents.V2.EphorteIdentity identity, System.Guid contextId, byte[] contentChunk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gecko.no/ephorte/services/documents/v2/Documents/EndCheckin", ReplyAction="http://www.gecko.no/ephorte/services/documents/v2/Documents/EndCheckinResponse")]
        void EndCheckin(Gecko.NCore.Client.Documents.V2.EphorteIdentity identity, System.Guid contextId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gecko.no/ephorte/services/documents/v2/Documents/CancelCheckin", ReplyAction="http://www.gecko.no/ephorte/services/documents/v2/Documents/CancelCheckinResponse" +
            "")]
        void CancelCheckin(Gecko.NCore.Client.Documents.V2.EphorteIdentity identity, System.Guid contextId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gecko.no/ephorte/services/documents/v2/Documents/BeginCheckout", ReplyAction="http://www.gecko.no/ephorte/services/documents/v2/Documents/BeginCheckoutResponse" +
            "")]
        System.Guid BeginCheckout(Gecko.NCore.Client.Documents.V2.EphorteIdentity identity, int documentId, int version, string variant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gecko.no/ephorte/services/documents/v2/Documents/ReadCheckoutChunk", ReplyAction="http://www.gecko.no/ephorte/services/documents/v2/Documents/ReadCheckoutChunkResp" +
            "onse")]
        byte[] ReadCheckoutChunk(Gecko.NCore.Client.Documents.V2.EphorteIdentity identity, System.Guid contextId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gecko.no/ephorte/services/documents/v2/Documents/EndCheckout", ReplyAction="http://www.gecko.no/ephorte/services/documents/v2/Documents/EndCheckoutResponse")]
        void EndCheckout(Gecko.NCore.Client.Documents.V2.EphorteIdentity identity, System.Guid contextId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gecko.no/ephorte/services/documents/v2/Documents/CancelCheckout", ReplyAction="http://www.gecko.no/ephorte/services/documents/v2/Documents/CancelCheckoutRespons" +
            "e")]
        void CancelCheckout(Gecko.NCore.Client.Documents.V2.EphorteIdentity identity, int journalpostId, int documentId, int version);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gecko.no/ephorte/services/documents/v2/Documents/EndDocumentRead", ReplyAction="http://www.gecko.no/ephorte/services/documents/v2/Documents/EndDocumentReadRespon" +
            "se")]
        void EndDocumentRead(Gecko.NCore.Client.Documents.V2.EphorteIdentity identity, System.Guid contextId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gecko.no/ephorte/services/documents/v2/Documents/BeginReadDocument", ReplyAction="http://www.gecko.no/ephorte/services/documents/v2/Documents/BeginReadDocumentResp" +
            "onse")]
        Gecko.NCore.Client.Documents.V2.BeginReadDocumentResponse BeginReadDocument(Gecko.NCore.Client.Documents.V2.EphorteIdentity identity, System.Nullable<int> documentId, System.Nullable<int> version, string variant, System.Nullable<int> journalpostId, System.Nullable<int> moeteId, System.Nullable<int> utvalgsbehandlingId, string sakType, string dokumentType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gecko.no/ephorte/services/documents/v2/Documents/ReadDocumentChunk", ReplyAction="http://www.gecko.no/ephorte/services/documents/v2/Documents/ReadDocumentChunkResp" +
            "onse")]
        byte[] ReadDocumentChunk(Gecko.NCore.Client.Documents.V2.EphorteIdentity identity, System.Guid contextId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gecko.no/ephorte/services/documents/v2/Documents/CancelReadDocument", ReplyAction="http://www.gecko.no/ephorte/services/documents/v2/Documents/CancelReadDocumentRes" +
            "ponse")]
        void CancelReadDocument(Gecko.NCore.Client.Documents.V2.EphorteIdentity identity, System.Guid contextId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DocumentsChannel : Gecko.NCore.Client.Documents.V2.Documents, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocumentsClient : System.ServiceModel.ClientBase<Gecko.NCore.Client.Documents.V2.Documents>, Gecko.NCore.Client.Documents.V2.Documents {
        
        public DocumentsClient() {
        }
        
        public DocumentsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DocumentsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Guid BeginCheckin(Gecko.NCore.Client.Documents.V2.EphorteIdentity identity, int documentId, int version, string variant) {
            return base.Channel.BeginCheckin(identity, documentId, version, variant);
        }
        
        public void WriteCheckinChunk(Gecko.NCore.Client.Documents.V2.EphorteIdentity identity, System.Guid contextId, byte[] contentChunk) {
            base.Channel.WriteCheckinChunk(identity, contextId, contentChunk);
        }
        
        public void EndCheckin(Gecko.NCore.Client.Documents.V2.EphorteIdentity identity, System.Guid contextId) {
            base.Channel.EndCheckin(identity, contextId);
        }
        
        public void CancelCheckin(Gecko.NCore.Client.Documents.V2.EphorteIdentity identity, System.Guid contextId) {
            base.Channel.CancelCheckin(identity, contextId);
        }
        
        public System.Guid BeginCheckout(Gecko.NCore.Client.Documents.V2.EphorteIdentity identity, int documentId, int version, string variant) {
            return base.Channel.BeginCheckout(identity, documentId, version, variant);
        }
        
        public byte[] ReadCheckoutChunk(Gecko.NCore.Client.Documents.V2.EphorteIdentity identity, System.Guid contextId) {
            return base.Channel.ReadCheckoutChunk(identity, contextId);
        }
        
        public void EndCheckout(Gecko.NCore.Client.Documents.V2.EphorteIdentity identity, System.Guid contextId) {
            base.Channel.EndCheckout(identity, contextId);
        }
        
        public void CancelCheckout(Gecko.NCore.Client.Documents.V2.EphorteIdentity identity, int journalpostId, int documentId, int version) {
            base.Channel.CancelCheckout(identity, journalpostId, documentId, version);
        }
        
        public void EndDocumentRead(Gecko.NCore.Client.Documents.V2.EphorteIdentity identity, System.Guid contextId) {
            base.Channel.EndDocumentRead(identity, contextId);
        }
        
        public Gecko.NCore.Client.Documents.V2.BeginReadDocumentResponse BeginReadDocument(Gecko.NCore.Client.Documents.V2.EphorteIdentity identity, System.Nullable<int> documentId, System.Nullable<int> version, string variant, System.Nullable<int> journalpostId, System.Nullable<int> moeteId, System.Nullable<int> utvalgsbehandlingId, string sakType, string dokumentType) {
            return base.Channel.BeginReadDocument(identity, documentId, version, variant, journalpostId, moeteId, utvalgsbehandlingId, sakType, dokumentType);
        }
        
        public byte[] ReadDocumentChunk(Gecko.NCore.Client.Documents.V2.EphorteIdentity identity, System.Guid contextId) {
            return base.Channel.ReadDocumentChunk(identity, contextId);
        }
        
        public void CancelReadDocument(Gecko.NCore.Client.Documents.V2.EphorteIdentity identity, System.Guid contextId) {
            base.Channel.CancelReadDocument(identity, contextId);
        }
    }
}
