//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gecko.NCore.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gecko.NCore.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The registry entry must have a valid CaseId..
        /// </summary>
        internal static string FunctionManagerExtensions_ApproveRegistryEntry_The_registry_entry_must_have_a_valid_CaseId {
            get {
                return ResourceManager.GetString("FunctionManagerExtensions_ApproveRegistryEntry_The_registry_entry_must_have_a_val" +
                        "id_CaseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The registry entry must have a valid Id..
        /// </summary>
        internal static string FunctionManagerExtensions_ApproveRegistryEntry_The_registry_entry_must_have_a_valid_Id {
            get {
                return ResourceManager.GetString("FunctionManagerExtensions_ApproveRegistryEntry_The_registry_entry_must_have_a_val" +
                        "id_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The must be at least one member in the Access Group..
        /// </summary>
        internal static string FunctionManagerExtensions_CreateAccessGroup_The_must_be_at_least_one_member_in_the_Access_Group {
            get {
                return ResourceManager.GetString("FunctionManagerExtensions_CreateAccessGroup_The_must_be_at_least_one_member_in_th" +
                        "e_Access_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The case must have a valid Id..
        /// </summary>
        internal static string FunctionManagerExtensions_The_case_must_have_a_valid_Id {
            get {
                return ResourceManager.GetString("FunctionManagerExtensions_The_case_must_have_a_valid_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recipient must have a valid Id..
        /// </summary>
        internal static string FunctionManagerExtensions_The_recipient_must_have_a_valid_Id {
            get {
                return ResourceManager.GetString("FunctionManagerExtensions_The_recipient_must_have_a_valid_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recipient must have a valid RegistryEntryId..
        /// </summary>
        internal static string FunctionManagerExtensions_The_recipient_must_have_a_valid_RegistryEntryId {
            get {
                return ResourceManager.GetString("FunctionManagerExtensions_The_recipient_must_have_a_valid_RegistryEntryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sender/recipient must have a valid Id..
        /// </summary>
        internal static string FunctionManagerExtensions_The_sender_recipient_must_have_a_valid_Id {
            get {
                return ResourceManager.GetString("FunctionManagerExtensions_The_sender_recipient_must_have_a_valid_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The task must have a valid Id..
        /// </summary>
        internal static string FunctionManagerExtensions_The_task_must_have_a_valid_Id {
            get {
                return ResourceManager.GetString("FunctionManagerExtensions_The_task_must_have_a_valid_Id", resourceCulture);
            }
        }
    }
}
